services:
  - type: web
    name: encuestascs2
    env: node
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: ASSET_ID
        sync: false
      - key: API_TOKEN
        sync: false
      - key: NOMBRE_PROYECTO
        value: "Encuesta Cantonal Rumiñahui - Septiembre - 2026"
      - key: CAMPO_ENCUESTADOR
        value: codencu
      - key: CAMPO_SUPERVISOR
        value: codsup
      - key: META_ENCUESTAS
        value: "900"
      - key: CACHE_TTL_SEGUNDOS
        value: 90
